### ISSUE TITLE
Error with contentDimensions and fallback values

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Taxonomy#5]
I've got following content dimensions setting in Neos 3.3

```yaml
Neos:
  ContentRepository:
    contentDimensions:
      language:
        default: en
        defaultPreset: en
        label: Sprache
        icon: icon-language
        presets:
          de:
            label: Deutsch
            values:
              - de
              - en
            uriSegment: de
          en:
            label: English
            values:
              - en
              - de
            uriSegment: en

```

If I try to add a vocabulary I got following error: 

```
Exception Code | 1487617770
-- | --
Neos\ContentRepository\Service\Exception\InvalidDimensionConfigurationException
201807121503158f6f3b
Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_ContentRepository_Service_FallbackGraphService.php
88
Packages/Application/Neos.ContentRepository/Classes/Service/FallbackGraphService.php
```

If I remove the fallback values everything works as expected…
